### ISSUE TITLE
Program hangs If I enter Fin=80000000

### ISSUE THREAD

**Issue by digidhamu** [liyanboy74/timer-frequency-calculator#1]
Looks like program hangs If I enter Fin=80000000. Could you please assist if I am doing anything wrong.

![TimerCalcIssue](https://github.com/liyanboy74/timer-frequency-calculator/assets/9908852/de78924c-98f0-4626-8c70-7158bec4fa3b)

**Comment by liyanboy74** [comment]
This is because it is also impossible to have a frequency with an error of 0 for input data.
You have to allow some margin of error.

![Screenshot 2023-10-26 082932](https://github.com/liyanboy74/timer-frequency-calculator/assets/64005694/f2a564be-fcc3-4b69-9571-4a7f613ecdd3)

**Comment by digidhamu** [comment]
Thanks for this advise and support.
